### ISSUE TITLE
visualize problem

### ISSUE THREAD

**Issue by Michelexiaoxiao** [mattpfr/lmanet#4]
@mattpfr 
Thank you very much for your code!
Is visualization intelligently entering five images at a time？
Looking forward for your reply!

**Comment by mattpfr** [comment]
@Michelexiaoxiao, I am a bit confused by your question, as the title changed as well several times. Do you still have a question / issue ?

**Comment by Michelexiaoxiao** [comment]
Thanks for your reply！ I have solved this problem！Thank you ery much！

**Comment by mattpfr** [comment]
Great to hear!
